'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminJoblist
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsearch As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsearch As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetails As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbwrno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbwrno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbsupplier1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsupplier1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblMessage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbprice1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbprice1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdate1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''trlist1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trlist1 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lnk_del1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_del1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbls1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_lssupplier_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lssupplier_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbnamefile1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbnamefile1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tb_lsprice1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsprice1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_lsdate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsdate1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsupplier2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsupplier2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''FileUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload2 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblMessage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbprice2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbprice2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdate2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''trlist2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trlist2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lnk_del2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_del2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbls2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbls2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_lssupplier_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lssupplier_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbnamefile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbnamefile2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tb_lsprice2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsprice2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_lsdate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsdate2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsupplier3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsupplier3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''FileUpload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload3 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblMessage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbprice3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbprice3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdate3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''trlist3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trlist3 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lnk_del3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_del3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbls3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbls3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_lssupplier_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lssupplier_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbnamefile3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbnamefile3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tb_lsprice3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsprice3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_lsdate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsdate3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsupplier4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsupplier4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''FileUpload4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload4 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblMessage4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbprice4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbprice4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdate4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''trlist4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trlist4 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lnk_del4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_del4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbls4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbls4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_lssupplier_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lssupplier_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbnamefile4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbnamefile4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tb_lsprice4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsprice4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_lsdate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsdate4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsupplier5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsupplier5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''FileUpload5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload5 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblMessage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbprice5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbprice5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdate5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''trlist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trlist5 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lnk_del5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_del5 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbls5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbls5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_lssupplier_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lssupplier_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbnamefile5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbnamefile5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload5 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tb_lsprice5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsprice5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_lsdate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lsdate5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbmessage_ls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmessage_ls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkquosave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkquosave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbwrno_workingdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbwrno_workingdate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_startpl_dt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_startpl_dt As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_endpl_dt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_endpl_dt As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lnksaveworkingdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksaveworkingdate As Global.System.Web.UI.WebControls.LinkButton
End Class
